apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: argocd-metrics-ext
  labels:
    tab: "Metrics"
    icon: "fa-chart"
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
    - web:
        url: https://github.com/crenshaw-dev/argocd-extension-metrics/raw/install-instructions/extensions/resource-metrics/resource-metrics-extention/ui/dist/extension.tar
