# build:
# 	yarn build
# 	curl -H 'X-JFrog-Art-Api:...' -T /Users/dsmith36/projects/intuit/argocd-ext-demo/ui/dist/extension.tar "https://artifact-preprod.intuit.com/artifactory/generic-local/personal/dsmith36/extension.tar"
# 	kubectl delete -f ./manifests/install.yaml -n argocd
# 	kubectl apply -f ./manifests/install.yaml -n argocd

# reapply:
# 	kubectl delete -f ./manifests/install.yaml -n argocd
# 	kubectl apply -f ./manifests/install.yaml -n argocd

# apply:
# 	kubectl apply -f ./manifests/install.yaml -n argocd

# delete:
# 	kubectl delete -f ./manifests/install.yaml -n argocd